In [1]:
import pprint

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
p = np.random.randint(-5, 5, [10,5]).astype("float32")
pprint.pprint(p)

array([[ 4., -3., -1., -2., -3.],
       [ 0., -5., -5.,  3.,  1.],
       [-2., -1.,  2.,  3.,  3.],
       [-1.,  3., -1., -1.,  0.],
       [-1., -2., -3.,  3., -4.],
       [ 4., -1.,  4., -3.,  2.],
       [ 1., -2.,  3.,  2., -3.],
       [ 4., -5., -1., -2.,  0.],
       [ 3.,  2.,  2., -3., -5.],
       [-1., -4.,  0.,  0., -5.]], dtype=float32)


In [5]:
b = tfp.bijectors.FillScaleTriL()

mvn = tfp.distributions.MultivariateNormalTriL(
    loc=p[:, 0:2],
    scale_tril=b.forward(p[:, 2:6])
)

cov = mvn.covariance()
pprint.pprint(cov)

mvnfc = tfp.distributions.MultivariateNormalFullCovariance(loc=p[:, 0:2], covariance_matrix=cov)

<tf.Tensor: shape=(10, 2, 2), dtype=float32, numpy=
array([[[ 2.3617030e-03, -9.7194709e-02],
        [-9.7194709e-02,  4.0981393e+00]],

       [[ 1.7246825e+00,  3.9398150e+00],
        [ 3.9398150e+00,  9.0000448e+00]],

       [[ 9.2939444e+00,  9.1457911e+00],
        [ 9.1457911e+00,  1.3523866e+01]],

       [[ 4.8046690e-01, -6.9315720e-01],
        [-6.9315720e-01,  1.0981392e+00]],

       [[ 3.2978298e-04,  5.4479785e-02],
        [ 5.4479785e-02,  9.0023613e+00]],

       [[ 4.5238657e+00, -6.3808146e+00],
        [-6.3808146e+00,  2.5145609e+01]],

       [[ 2.3617030e-03,  9.7194709e-02],
        [ 9.7194709e-02,  1.3293944e+01]],

       [[ 4.8046690e-01, -1.3863144e+00],
        [-1.3863144e+00,  4.0981393e+00]],

       [[ 4.5230314e-05, -2.0176046e-02],
        [-2.0176046e-02,  1.3523866e+01]],

       [[ 4.5230314e-05,  0.0000000e+00],
        [ 0.0000000e+00,  4.8046690e-01]]], dtype=float32)>
Instructions for updating:
`MultivariateNormalFullCovariance` is depreca

In [6]:
x = np.random.randint(-9, 9, [10,2]).astype("float32")
pprint.pprint(x)

loss = mvn.log_prob(x)
pprint.pprint(loss)

loss = mvnfc.log_prob(x)
pprint.pprint(loss)

array([[-8.,  5.],
       [ 1.,  3.],
       [ 1., -6.],
       [-9.,  4.],
       [-4.,  2.],
       [ 4.,  6.],
       [ 8., -6.],
       [-5., -3.],
       [-5., -6.],
       [ 2., -1.]], dtype=float32)
<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.2331341e+06, -3.6113141e+05, -1.1180708e+01, -6.3305231e+02,
       -5.2856192e+07, -5.5008249e+00, -1.4963434e+04, -3.0114246e+03,
       -2.1213210e+06, -9.9496641e+04], dtype=float32)>
<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.2331326e+06, -3.6441562e+05, -1.1180708e+01, -6.3305249e+02,
       -5.2865268e+07, -5.5008249e+00, -1.4963434e+04, -3.0114209e+03,
       -2.1213210e+06, -9.9496641e+04], dtype=float32)>


In [ ]:
tf.reduce_mean(loss, axis=-1)

In [7]:
f = tfp.bijectors.FillTriangular()
f.forward([1.0, 2.0, 3.0])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 0.],
       [2., 1.]], dtype=float32)>