In [36]:
import pprint

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

In [47]:
p = np.random.randint(-5, 5, [10,5]).astype("float32")
pprint.pprint(p)

array([[ 3., -4.,  0.,  1., -1.],
       [ 1.,  2.,  3., -4., -5.],
       [-1.,  0., -5., -5.,  4.],
       [ 3., -3.,  2., -2., -5.],
       [ 1., -5.,  0.,  1., -2.],
       [-5., -2.,  2.,  0., -2.],
       [-3., -1., -5., -5.,  4.],
       [-1., -1.,  0.,  2., -2.],
       [-2.,  3.,  2., -3.,  4.],
       [ 1.,  3.,  2.,  1., -3.]], dtype=float32)


In [48]:
b = tfp.bijectors.FillScaleTriL()

mvn = tfp.distributions.MultivariateNormalTriL(
    loc=p[:, 0:2],
    scale_tril=b.forward(p[:, 2:6])
)

mvn.covariance()

<tf.Tensor: shape=(10, 2, 2), dtype=float32, numpy=
array([[[ 9.8139174e-02,  3.1327173e-01],
        [ 3.1327173e-01,  1.4804668e+00]],

       [[ 4.5230314e-05, -2.6901394e-02],
        [-2.6901394e-02,  2.5293945e+01]],

       [[ 1.6145609e+01, -2.0090799e+01],
        [-2.0090799e+01,  2.5000046e+01]],

       [[ 4.5230314e-05, -1.3450697e-02],
        [-1.3450697e-02,  8.5238657e+00]],

       [[ 1.6113255e-02,  1.2693800e-01],
        [ 1.2693800e-01,  1.4804668e+00]],

       [[ 1.6113255e-02,  0.0000000e+00],
        [ 0.0000000e+00,  4.5238657e+00]],

       [[ 1.6145609e+01, -2.0090799e+01],
        [-2.0090799e+01,  2.5000046e+01]],

       [[ 1.6113255e-02,  2.5387600e-01],
        [ 2.5387600e-01,  4.4804668e+00]],

       [[ 1.6145609e+01, -1.2054480e+01],
        [-1.2054480e+01,  1.3523866e+01]],

       [[ 2.3617030e-03,  4.8597354e-02],
        [ 4.8597354e-02,  5.5238657e+00]]], dtype=float32)>

In [54]:
x = np.random.randint(-9, 9, [10,2]).astype("float32")
pprint.pprint(x)

mvn.log_prob(x)

array([[-6., -5.],
       [ 7., -2.],
       [-9., -2.],
       [-6.,  1.],
       [-9.,  2.],
       [-6.,  1.],
       [ 7.,  4.],
       [ 0., -2.],
       [ 3., -3.],
       [-3.,  5.]], dtype=float32)


<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.2131495e+03, -1.0815402e+06, -1.5798850e+06, -1.6847775e+06,
       -1.0759548e+04, -3.2553581e+01, -3.3636298e+06, -3.2260580e+02,
       -5.3255825e+00, -4.1725669e+03], dtype=float32)>