In [1]:
import pprint

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
p = np.random.randint(-5, 5, [10,5]).astype("float32")
pprint.pprint(p)

array([[-2.,  2.,  0., -1., -5.],
       [-1.,  0.,  3., -2.,  0.],
       [-5.,  1., -5., -1., -3.],
       [-1.,  4., -5.,  3., -3.],
       [-2., -4.,  3., -3., -3.],
       [ 0.,  2.,  1., -1.,  4.],
       [ 3.,  2.,  2.,  0., -4.],
       [-4., -4.,  0., -4., -3.],
       [-1., -4., -2.,  0.,  0.],
       [ 4.,  4.,  0.,  1., -2.]], dtype=float32)


In [3]:
b = tfp.bijectors.FillScaleTriL()

mvn = tfp.distributions.MultivariateNormalTriL(
    loc=p[:, 0:2],
    scale_tril=b.forward(p[:, 2:6])
)

mvn.covariance()

<tf.Tensor: shape=(10, 2, 2), dtype=float32, numpy=
array([[[ 4.5230314e-05, -6.7253485e-03],
        [-6.7253485e-03,  1.4804668e+00]],

       [[ 4.8046690e-01, -1.3863144e+00],
        [-1.3863144e+00,  1.3293944e+01]],

       [[ 2.3617030e-03, -4.8597354e-02],
        [-4.8597354e-02,  1.0000452e+00]],

       [[ 2.3617030e-03,  1.4579207e-01],
        [ 1.4579207e-01,  9.0000448e+00]],

       [[ 2.3617030e-03, -1.4579207e-01],
        [-1.4579207e-01,  1.8293945e+01]],

       [[ 1.6145609e+01, -4.0181599e+00],
        [-4.0181599e+00,  2.7246823e+00]],

       [[ 3.2978298e-04,  0.0000000e+00],
        [ 0.0000000e+00,  4.5238657e+00]],

       [[ 2.3617030e-03, -1.9438942e-01],
        [-1.9438942e-01,  1.6480467e+01]],

       [[ 4.8046690e-01,  0.0000000e+00],
        [ 0.0000000e+00,  1.6113255e-02]],

       [[ 1.6113255e-02,  1.2693800e-01],
        [ 1.2693800e-01,  1.4804668e+00]]], dtype=float32)>

In [4]:
x = np.random.randint(-9, 9, [10,2]).astype("float32")
pprint.pprint(x)

loss = mvn.log_prob(x)

array([[ 6., -8.],
       [-4.,  8.],
       [-4., -5.],
       [-3., -8.],
       [-6., -6.],
       [ 6.,  1.],
       [-4., -3.],
       [ 1.,  3.],
       [-5.,  6.],
       [-3., -9.]], dtype=float32)


In [5]:
tf.reduce_mean(loss, axis=-1)

<tf.Tensor: shape=(), dtype=float32, numpy=-14212331.0>

In [7]:
f = tfp.bijectors.FillTriangular()
f.forward([1.0, 2.0, 3.0])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 0.],
       [2., 1.]], dtype=float32)>