In [1]:
import pprint

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

import custom_loss

In [2]:
y_true = np.random.rand(10,2).astype("float32")
pprint.pprint(y_true)

array([[0.6250468 , 0.38855532],
       [0.12832336, 0.6437322 ],
       [0.81339115, 0.949936  ],
       [0.2029405 , 0.5719799 ],
       [0.7731557 , 0.7534841 ],
       [0.33414033, 0.8554071 ],
       [0.04793052, 0.9936554 ],
       [0.14036794, 0.66519284],
       [0.6825447 , 0.3027963 ],
       [0.2739867 , 0.05989623]], dtype=float32)


In [3]:
param = np.random.rand(10,5).astype("float32")
pprint.pprint(param)

array([[0.47692075, 0.58808196, 0.7436506 , 0.95242894, 0.07275046],
       [0.65278476, 0.00579681, 0.20037976, 0.38588873, 0.6885354 ],
       [0.9030716 , 0.09160417, 0.14137532, 0.06906988, 0.1718278 ],
       [0.02462869, 0.17891888, 0.66368634, 0.12147601, 0.3603253 ],
       [0.5343513 , 0.13434151, 0.7880287 , 0.7662276 , 0.4496839 ],
       [0.5685111 , 0.5097001 , 0.0715472 , 0.18482389, 0.26562706],
       [0.07339371, 0.00709152, 0.1314951 , 0.77342606, 0.7697801 ],
       [0.56667686, 0.84961295, 0.45058277, 0.94791466, 0.9894854 ],
       [0.7941179 , 0.3611085 , 0.14985774, 0.1401997 , 0.31829447],
       [0.45989713, 0.9105124 , 0.19118096, 0.6552858 , 0.18379489]],
      dtype=float32)


In [4]:
A = tf.stack(
    (
        param[:, 3] * tf.math.sqrt(1.0 - tf.math.square(param[:, 4])),
        param[:, 3] * param[:, 4],
        param[:, 2],
    ),
    axis=1
)
pprint.pprint(A)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.9499052 , 0.06928964, 0.7436506 ],
       [0.27984756, 0.26569805, 0.20037976],
       [0.06804261, 0.01186813, 0.14137532],
       [0.11331607, 0.04377088, 0.66368634],
       [0.6843851 , 0.3445602 , 0.7880287 ],
       [0.17818426, 0.04909423, 0.0715472 ],
       [0.49368492, 0.59536797, 0.1314951 ],
       [0.13709961, 0.9379477 , 0.45058277],
       [0.13290818, 0.04462479, 0.14985774],
       [0.6441227 , 0.12043817, 0.19118096]], dtype=float32)>


In [5]:
loss = custom_loss.compute_bivariate_normal_NLL(y_true, param)
pprint.pprint(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=12.034925>
